# .github/dependabot.yml
version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: monthly
    groups:
      react-runtime:
        patterns:
          - "react"
          - "react-dom"
    ignore:
      - dependency-name: "@types/node"
        update-types: ["version-update:semver-major"]
