name: Release PR

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  call_reusable_changesets_pr:
    name: Call Reusable Changesets PR Workflow
    uses: DelGrosso-Foods-Inc/github-workflows/.github/workflows/reusable-changesets-pr.yml@v1.0.0
    with:
      node-version: '20'
